---
name: Release Assets
on:
  release:
    types: [published]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    name: Generate and Upload SBOM
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install cargo-cyclonedx
        run: cargo install cargo-cyclonedx

      - name: Generate SBOM
        run: cargo cyclonedx --format xml --override-filename urx.cdx

      - name: Upload SBOM to release
        uses: softprops/action-gh-release@v2
        with:
          files: urx.cdx.xml
        env:
          GITHUB_TOKEN: ${{ secrets.URX_PUBLISH_TOKEN }}
